{% set name = "bed-reader" %}
{% set version = "0.2.24" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Can't use the standard pattern because of the hypen/underscore remapping.
  url: https://pypi.io/packages/source/b/bed-reader/bed_reader-{{ version }}.tar.gz
  sha256: cf0fabe11dd8a1a98405ffcc91435a03ae0791b46a604c43d4e4c495e9e275c5

build:
  number: 0
  # Disabling Windows builds 2022/01 because of obscure build system problems.01/2022
  skip: true  # [py<37,win]

requirements:
  build:
    - {{ compiler('c') }}
    - rust
    - maturin

  host:
    - python
    - pip
    - maturin
    - toml

  run:
    - python
    # Versions taken from requirements.txt
    - numpy >=1.13.3
    - pandas >=0.25.1
    - pooch >=1.1.1

test:
  imports:
    - bed_reader

about:
  home: https://github.com/fastlmm/bed-reader
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Read and write the PLINK BED format, simply and efficiently.
  doc_url: https://fastlmm.github.io/bed-reader/
  dev_url: https://github.com/fastlmm/bed-reader

extra:
  recipe-maintainers:
    - jeromekelleher
    - CarlKCarlK
