{% set name = "bed-reader" %}
{% set version = "0.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Can't use the standard pattern because of the hypen/underscore remapping.
  url: https://pypi.io/packages/source/b/bed-reader/bed_reader-{{ version }}.tar.gz
  sha256: 2b13a0d88eaac27f01aba4429c79c195da7c5798f63a0497cfa566862b04faa3

build:
  number: 0
  skip: true  # [py<37]

requirements:
  build:
    - {{ compiler('c') }}
    - rust
    - maturin

  host:
    - python
    - pip
    - maturin
    - toml

  run:
    - python
    # Versions taken from requirements.txt
    - numpy >=1.13.3
    - pandas >=0.25.1
    - pooch >=1.1.1

test:
  imports:
    - bed_reader

about:
  home: https://github.com/fastlmm/bed-reader
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Read and write the PLINK BED format, simply and efficiently.
  doc_url: https://fastlmm.github.io/bed-reader/
  dev_url: https://github.com/fastlmm/bed-reader

extra:
  recipe-maintainers:
    - jeromekelleher
    - CarlKCarlK
