{% set name = "bed-reader" %}
{% set version = "0.2.36" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # Can't use the standard pattern because of the hypen/underscore remapping.
  url: https://pypi.io/packages/source/b/bed-reader/bed_reader-{{ version }}.tar.gz
  sha256: 9bbbd28117deef3ca00ec67553bd5f8fa8bd19919f316cb77316e6230158cca4

build:
  number: 2
  skip: true  # [py<37]

requirements:
  build:
    # Support for osx_arm64 as recommended by
    # https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/#how-to-add-a-osx-arm64-build-to-a-feedstock
    - {{ compiler('rust') }}
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - maturin >=0.14,<0.15                   # [build_platform != target_platform]

  host:
    - python
    - pip
    - maturin >=0.14,<0.15
    - cython
    - numpy
    - pybind11

  run:
    - python
    # Versions taken from pyproject.toml
    - numpy >=1.13.3
    - pandas >=0.25.1
    - pooch >=1.4.0
    - chardet >=5.1.0

test:
  imports:
    - bed_reader

about:
  home: https://github.com/fastlmm/bed-reader
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: Read and write the PLINK BED format, simply and efficiently.
  doc_url: https://fastlmm.github.io/bed-reader/
  dev_url: https://github.com/fastlmm/bed-reader

extra:
  recipe-maintainers:
    - jeromekelleher
    - CarlKCarlK
